version: '3'
services:
  web:
    image: java_springv1_codelingo_v2
    build: .
    ports:
      - "8200:8085"
    volumes:
      - persistent_volume:/app/volumes
    restart: unless-stopped
volumes:
  persistent_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/ubuntu/tri3_codelingo_8200/volumes 
